#!/bin/bash
gcc -fPIC -c add.c;
gcc -fPIC -c sub.c;
gcc -fPIC -c mpy.c;
gcc -fPIC -c div.c;
export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
ar rcs libas.a add.o sub.o;
gcc mpy.o div.o -shared -o libmd.so
gcc main.c libas.a libmd.so -o main;
